package capabilities

// catalog is the frozen first-GA REST↔MCP table. Order is the docs/05
// capability list; do not reorder or rename in place.
func catalog() []Capability {
	return []Capability{
		{
			ID: HealthLive, Title: "Health live", Version: VersionTag,
			Description: "Process liveness. Not an MCP tool.",
			Idempotent:  true, RESTOnly: true,
			REST: []RESTBinding{{Method: "GET", Path: "/v1/health/live"}},
		},
		{
			ID: HealthReady, Title: "Health ready", Version: VersionTag,
			Description: "SMTP bound, store initialized, and management bound or explicitly off. Not an MCP tool.",
			Idempotent:  true, RESTOnly: true,
			REST: []RESTBinding{{Method: "GET", Path: "/v1/health/ready"}},
		},
		{
			ID: VersionGet, Title: "Version", Version: VersionTag,
			Description:    "Build and protocol versions.",
			RequiredScopes: []string{ScopeMailRead}, Idempotent: true,
			OutputSchema:   &SchemaRef{Name: "Version"},
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/version"}},
			MCP:            &MCPBinding{Tools: []string{"mail_version_get"}},
			ServiceMethods: []string{"Version"},
		},
		{
			ID: CapabilitiesGet, Title: "Capabilities", Version: VersionTag,
			Description:    "Capability list and protocol metadata.",
			RequiredScopes: []string{ScopeMailRead}, Idempotent: true,
			OutputSchema:   &SchemaRef{Name: "CapabilityView"},
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/capabilities"}},
			MCP:            &MCPBinding{Tools: []string{"mail_capabilities_get"}, Resources: []string{"labmail://capabilities"}},
			ServiceMethods: []string{"Capabilities"},
		},
		{
			ID: StatusGet, Title: "Agent status", Version: VersionTag,
			Description:    "Listeners, store stats, and revisions.",
			RequiredScopes: []string{ScopeMailRead}, Idempotent: true,
			OutputSchema:   &SchemaRef{Name: "Status"},
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/status"}},
			MCP:            &MCPBinding{Tools: []string{"mail_status_get"}, Resources: []string{"labmail://status"}},
			ServiceMethods: []string{"Status"},
		},
		{
			ID: SchemaGet, Title: "Config schema", Version: VersionTag,
			Description:    "Published v1alpha1 config JSON Schema.",
			RequiredScopes: []string{ScopeMailRead}, Idempotent: true,
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/schema/config"}},
			MCP:            &MCPBinding{Tools: []string{"mail_schema_get"}, Resources: []string{"labmail://schema/config"}},
			ServiceMethods: []string{"ConfigSchema"},
		},
		{
			ID: StateGet, Title: "Get state", Version: VersionTag,
			Description:    "Redacted spec plus revision metadata.",
			RequiredScopes: []string{ScopeMailRead}, Idempotent: true,
			OutputSchema:   &SchemaRef{Name: "StateView"},
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/state"}},
			MCP:            &MCPBinding{Tools: []string{"mail_state_get"}, Resources: []string{"labmail://state"}},
			ServiceMethods: []string{"GetState"},
		},
		{
			ID: StateValidate, Title: "Validate", Version: VersionTag,
			Description:    "Validate a candidate document and/or operations without writing.",
			RequiredScopes: []string{ScopeMailAdmin}, Idempotent: true,
			InputSchema:    &SchemaRef{Name: "ValidateIn"},
			OutputSchema:   &SchemaRef{Name: "Plan"},
			REST:           []RESTBinding{{Method: "POST", Path: "/v1/state:validate"}},
			MCP:            &MCPBinding{Tools: []string{"mail_state_validate"}},
			ServiceMethods: []string{"Validate"},
		},
		{
			ID: StateExport, Title: "Export", Version: VersionTag,
			Description:    "Canonical desired-state export plus drift material.",
			RequiredScopes: []string{ScopeMailAdmin}, Idempotent: true,
			OutputSchema:   &SchemaRef{Name: "Export"},
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/state:export"}},
			MCP:            &MCPBinding{Tools: []string{"mail_state_export"}},
			ServiceMethods: []string{"Export"},
		},
		{
			ID: StateReset, Title: "Reset", Version: VersionTag,
			Description:    "Reread the bootstrap mount, wipe the inbox, and swap. Never writes the file.",
			RequiredScopes: []string{ScopeMailAdmin}, Mutating: true,
			InputSchema:    &SchemaRef{Name: "ResetIn"},
			OutputSchema:   &SchemaRef{Name: "ApplyResult"},
			REST:           []RESTBinding{{Method: "POST", Path: "/v1/state:reset"}},
			MCP:            &MCPBinding{Tools: []string{"mail_state_reset"}},
			ServiceMethods: []string{"Reset"},
		},
		{
			ID: ChangesPlan, Title: "Plan", Version: VersionTag,
			Description:    "Dry-run operations against the active snapshot.",
			RequiredScopes: []string{ScopeMailAdmin}, Idempotent: true,
			InputSchema:    &SchemaRef{Name: "ChangeIn"},
			OutputSchema:   &SchemaRef{Name: "Plan"},
			REST:           []RESTBinding{{Method: "POST", Path: "/v1/changes:plan"}},
			MCP:            &MCPBinding{Tools: []string{"mail_change_plan"}},
			ServiceMethods: []string{"Plan"},
		},
		{
			ID: ChangesApply, Title: "Apply", Version: VersionTag,
			Description:    "Apply operations. expectedRevision is required.",
			RequiredScopes: []string{ScopeMailAdmin}, Mutating: true, Idempotent: true,
			InputSchema:    &SchemaRef{Name: "ChangeIn"},
			OutputSchema:   &SchemaRef{Name: "ApplyResult"},
			REST:           []RESTBinding{{Method: "POST", Path: "/v1/changes:apply"}},
			MCP:            &MCPBinding{Tools: []string{"mail_change_apply"}},
			ServiceMethods: []string{"Apply"},
		},
		{
			ID: SessionCreate, Title: "Create session", Version: VersionTag,
			Description: "Cookie + CSRF session for the inbox UI. Implemented in SEC-001.",
			Idempotent:  false, RESTOnly: true, Mutating: true,
			REST: []RESTBinding{{Method: "POST", Path: "/v1/session"}},
		},
		{
			ID: SessionDelete, Title: "Delete session", Version: VersionTag,
			Description: "Clear the inbox UI session cookie. Implemented in SEC-001.",
			Idempotent:  true, RESTOnly: true, Mutating: true,
			REST: []RESTBinding{{Method: "DELETE", Path: "/v1/session"}},
		},
		{
			ID: SessionGet, Title: "Get session", Version: VersionTag,
			Description: "Current session principal. Implemented in SEC-001.",
			Idempotent:  true, RESTOnly: true,
			REST: []RESTBinding{{Method: "GET", Path: "/v1/session"}},
		},
		{
			ID: EventsStream, Title: "Events stream", Version: VersionTag,
			Description:    "REST SSE inbox events. MCP uses subscriptions/listen URI-only notify.",
			RequiredScopes: []string{ScopeMailRead}, Idempotent: true, DifferentBinding: true,
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/events/stream"}},
			MCP:            &MCPBinding{Resources: []string{"labmail://messages"}},
			ServiceMethods: []string{"Subscribe"},
		},
		{
			ID: MessagesList, Title: "List messages", Version: VersionTag,
			Description:    "Cursor-paginated inbox list. HMAC cursors bind storeGeneration.",
			RequiredScopes: []string{ScopeMailRead}, Idempotent: true,
			OutputSchema:   &SchemaRef{Name: "MessageList"},
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/messages"}},
			MCP:            &MCPBinding{Tools: []string{"mail_messages_list"}, Resources: []string{"labmail://messages"}},
			ServiceMethods: []string{"ListMessages"},
		},
		{
			ID: MessagesGet, Title: "Get message", Version: VersionTag,
			Description:    "Full message. markRead defaults to false on the native path.",
			RequiredScopes: []string{ScopeMailRead}, Idempotent: true,
			OutputSchema:   &SchemaRef{Name: "Message"},
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/messages/{id}"}},
			MCP:            &MCPBinding{Tools: []string{"mail_message_get"}, Resources: []string{"labmail://messages/{id}"}},
			ServiceMethods: []string{"GetMessage"},
		},
		{
			ID: MessagesRaw, Title: "Raw message", Version: VersionTag,
			Description:    "RFC 822 source (message/rfc822).",
			RequiredScopes: []string{ScopeMailRead}, Idempotent: true,
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/messages/{id}/raw"}},
			MCP:            &MCPBinding{Tools: []string{"mail_message_raw_get"}},
			ServiceMethods: []string{"GetMessage"},
		},
		{
			ID: MessagesHTML, Title: "HTML body", Version: VersionTag,
			Description:    "Raw HTML body with no CSP. Not the sandboxed preview.",
			RequiredScopes: []string{ScopeMailRead}, Idempotent: true,
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/messages/{id}/html"}},
			MCP:            &MCPBinding{Tools: []string{"mail_message_html_get"}},
			ServiceMethods: []string{"GetMessage"},
		},
		{
			ID: MessagesPreview, Title: "HTML preview", Version: VersionTag,
			Description:    "CSP document for the sandboxed iframe. cid: rewritten to data: URLs.",
			RequiredScopes: []string{ScopeMailRead}, Idempotent: true, RESTOnly: true,
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/messages/{id}/preview"}},
			ServiceMethods: []string{"GetMessage"},
		},
		{
			ID: MessagesDelete, Title: "Delete message", Version: VersionTag,
			Description:    "Delete one message by id.",
			RequiredScopes: []string{ScopeMailWrite}, Mutating: true, Idempotent: true,
			REST:           []RESTBinding{{Method: "DELETE", Path: "/v1/messages/{id}"}},
			MCP:            &MCPBinding{Tools: []string{"mail_message_delete"}},
			ServiceMethods: []string{"DeleteMessage"},
		},
		{
			ID: MessagesClear, Title: "Clear inbox", Version: VersionTag,
			Description:    "Delete every message. Does not bump epoch.",
			RequiredScopes: []string{ScopeMailWrite}, Mutating: true, Idempotent: true,
			REST:           []RESTBinding{{Method: "DELETE", Path: "/v1/messages"}},
			MCP:            &MCPBinding{Tools: []string{"mail_messages_clear"}},
			ServiceMethods: []string{"ClearMessages"},
		},
		{
			ID: MessagesReadAll, Title: "Mark all read", Version: VersionTag,
			Description:    "Set every read bit. Does not bump storeGeneration.",
			RequiredScopes: []string{ScopeMailWrite}, Mutating: true, Idempotent: true,
			REST:           []RESTBinding{{Method: "POST", Path: "/v1/messages:read-all"}},
			MCP:            &MCPBinding{Tools: []string{"mail_messages_read_all"}},
			ServiceMethods: []string{"MarkAllRead"},
		},
		{
			ID: MessagesWait, Title: "Wait for message", Version: VersionTag,
			Description:    "Block until a matching message arrives or the timeout fires.",
			RequiredScopes: []string{ScopeMailRead}, Idempotent: true,
			InputSchema:    &SchemaRef{Name: "WaitIn"},
			OutputSchema:   &SchemaRef{Name: "Message"},
			REST:           []RESTBinding{{Method: "POST", Path: "/v1/messages:wait"}},
			MCP:            &MCPBinding{Tools: []string{"mail_messages_wait"}},
			ServiceMethods: []string{"Wait"},
		},
		{
			ID: MessagesExtract, Title: "Extract tokens", Version: VersionTag,
			Description:    "Extract URLs and OTP-like tokens using the frozen RE2 set.",
			RequiredScopes: []string{ScopeMailRead}, Idempotent: true,
			OutputSchema:   &SchemaRef{Name: "ExtractResult"},
			REST:           []RESTBinding{{Method: "POST", Path: "/v1/messages/{id}:extract"}},
			MCP:            &MCPBinding{Tools: []string{"mail_message_extract"}},
			ServiceMethods: []string{"Extract"},
		},
		{
			ID: AttachmentsGet, Title: "Get attachment", Version: VersionTag,
			Description:    "Download one attachment. Content-Disposition: attachment.",
			RequiredScopes: []string{ScopeMailRead}, Idempotent: true,
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/messages/{id}/attachments/{attId}"}},
			MCP:            &MCPBinding{Tools: []string{"mail_attachment_get"}},
			ServiceMethods: []string{"GetMessage"},
		},
		{
			ID: AuditList, Title: "Audit list", Version: VersionTag,
			Description:    "Query recent in-memory audit events.",
			RequiredScopes: []string{ScopeMailAuditRead}, Idempotent: true,
			InputSchema:    &SchemaRef{Name: "AuditQuery"},
			OutputSchema:   &SchemaRef{Name: "AuditList"},
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/audit"}},
			MCP:            &MCPBinding{Tools: []string{"mail_audit_query"}, Resources: []string{"labmail://audit/recent"}},
			ServiceMethods: []string{"QueryAudit"},
		},
		{
			ID: AuditGet, Title: "Audit get", Version: VersionTag,
			Description:    "Get one audit event by ID.",
			RequiredScopes: []string{ScopeMailAuditRead}, Idempotent: true,
			OutputSchema:   &SchemaRef{Name: "AuditEvent"},
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/audit/{eventId}"}},
			MCP:            &MCPBinding{Tools: []string{"mail_audit_get"}},
			ServiceMethods: []string{"GetAudit"},
		},
		{
			ID: MetricsGet, Title: "Metrics", Version: VersionTag,
			Description:    "OpenMetrics text. Served only when observability.metrics.publicPath is true.",
			RequiredScopes: []string{ScopeMailRead}, Idempotent: true, RESTOnly: true,
			REST: []RESTBinding{{Method: "GET", Path: "/v1/metrics"}},
		},
	}
}
